version: '3'

services:
  web:
    image: inventory-management-app
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SETTINGS_MODULE=InventoryManager.settings
